### PR TITLE
Move Spring Docs

### PR DESCRIPTION
**Pull request by joshuaellis**
### Overview

This is a move over of the spring docs. Because it was it's own site (built with `mdx` #foresight) it is a little richer than the readme's we normally have. There are a few custom components such as a high use of `react-live` and our own `Demo` previewing with codesandboxes that are generated from the srccode of spring (so they're always up to date).

### Technical challenges moving over

In no particular order:
1. I can't figure out for the life of me how to get the routing to work - `/react-spring` returns a 404 (maybe im dumb)
2. The docs use `react-live` in a few places to demonstrate code examples that are editable
3. The docs import the demos from a `react-spring` submodule in the repo so they're always up to date.
4. The docs use a tweet masonry grid to gloat how "influential" devs love the library

### My thoughts

I suppose issue 1. is simple enough, i just need a little help. Issue 2. is probably easily solvable, we could either port the code over or there may be a better solution? I didn't spend too long looking for a solution previously. Issue 4 is the same, I can just move the code over and it can be a component in this site.

I'd say issue 3 is the biggest one & i'm not sure the best way to solve it. Would love to hear suggestions 🎉

### CODE REVIEW

**Comment by joshuaellis** [comment]
* TweetGrid component – https://github.com/pmndrs/react-spring.io/blob/master/src/components/Grids/GridTweets.tsx
* CodeBlock component – https://github.com/pmndrs/react-spring.io/blob/master/src/components/CodeBlock/index.tsx
* Demo components – https://github.com/pmndrs/react-spring.io/tree/master/src/components/Demo 

The demo component takes a child that is normally the `App.tsx` from a demo pulled from the `react-spring` repo (which is a submodule). This way it can render in site & then there's an external link to open the sandbox.

**Comment by joshuaellis** [comment]
image

the side nav seems to have a problem and a side note, are we supposed to be able to switch between docs somewhere? I couldn't see where to do that 🤔

**Comment by SaraVieira** [comment]
No idea what that is but the switcher is not live yet :/

It's also a PR

**Comment by joshuaellis** [comment]
I have jumped the gun! nw

**Comment by SaraVieira** [comment]
Thats why I was talking about merging but not announcing because there is no switcher and no homepage

**Comment by joshuaellis** [comment]
You've done a really amazing job ⭐ this PR has my approval 🚀

**Pull request merged**
