### PR TITLE
docs(R3F): Add haunted house example

### PR DESCRIPTION
**Pull request by hazem3500**
Add the haunted house example from Three.js Journey Course

### CODE REVIEW

**Comment by hazem3500** [comment]
I've updated the thumbnail for the codesandbox but I don't know how to make that reflect in the docs 😅

**Comment by CodyJasonBennett** [comment]
It's updated, but you might have to redeploy for changes to be reflected. The image appears from the remote APIs and on local builds.

**Comment by hazem3500** [comment]
@CodyJasonBennett oh, do you know how can I trigger vercel to redeploy? I don't want to add an empty commit 😅, is there another way?

**Comment by CodyJasonBennett** [comment]
I had to get creative but I created a temp branch from this PR, which had Vercel re-deploy it:
 - https://website-r7keit0pa-pmndrs.vercel.app/react-three-fiber/getting-started/examples

image

Might need some tags though.

**Comment by drcmda** [comment]
tbh im not sure if it's a good fit. these demos are mostly very very dense and simplified, and show specific use cases or features. that one journey thing is probably enough.

but could we maybe open a repo on poimandres and collect all the journey demos there? this way people could also contribute and re-shape, simplify them. imo that's what im mostly after: showing how much code falls away. are you interested @hazem3500 ?

**Comment by hazem3500** [comment]
hmmmmmm 🤔, I like the idea of people being able to contribute to optimize/simplify the examples

If it was in a repo, would I still be able to develop using codesandbox? I like codesandbox because it removes the friction of setting up an environment and it makes the example easily sharable

So yup, @drcmda I would be interested in the idea 😁, I'll probably be submitting other examples too soon!

Another idea is to add a **Community Examples** section at the bottom, where people can submit their own examples

**Comment by CodyJasonBennett** [comment]
My worry with this is how it would integrate with #86. A separate repo would work to keep activity clean on the R3F repo, but I don't think it should extend to library docs but instead examples/community resources.

**Comment by hazem3500** [comment]
Hmmmmm, so if I understand correctly, we want the community examples to live on a separate repo, then we'll connect them with [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote)? and we don't want them to be in the docs, we want them to be in community examples/resources?

So is the "community examples/resources" separate from the docs or will it be a page inside the docs?
And would I be able to contribute in the separate repo through codesandbox? or will I have to copy the code-over and then make a PR?

**Comment by drcmda** [comment]
> hmmmmmm 🤔, I like the idea of people being able to contribute to optimize/simplify the examples

there's no need for it for now. unless a demo really warrants it, but even then we'd have to fork the sandbox so that we control it for maintenance reasons.

> If it was in a repo, would I still be able to develop using codesandbox? I like codesandbox because it removes the friction of setting up an environment and it makes the example easily sharable

this would probably have to be a vite project. single demos could be cast into csb's.

> Another idea is to add a **Community Examples** section at the bottom, where people can submit their own examples

imo the examples page is almost unusable as it is. it loads really slow, is not searchable, and the sandboxes are too many.  i don't think that people are really going through them in its current shape. community examples would make it worse atm.

maybe like threejs does it, a separate page with just linked thumbnails.

**Comment by hazem3500** [comment]
So the suggestion here is to defer this PR until we add a separate page for community examples (like how Three.js does it), then add the haunted house demo there, right?

**Comment by CodyJasonBennett** [comment]
Moved to https://github.com/pmndrs/threejs-journey.

**Pull request closed without merging**
